// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:080cd85b-773f-4052-8fe7-23b2df40c88b',
    'aws_cognito_region': 'us-west-2',
    'aws_mobile_analytics_app_id': 'cba776e280134dfe89651321432e2eed',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'e8e75dfd-bd7e-4450-ab66-8b9bab2041e4',
    'aws_project_name': 'PinpointTest',
    'aws_project_region': 'us-west-2',
    'aws_push_apns': 'enable',
    'aws_push_pinpoint': 'enable',
    'aws_resource_name_prefix': 'pinpointtest-mobilehub-1386580090',
}

export default awsmobile;
